version: "3"
services:
  backend:
    build: .
    image: oshri-portfolio-back
    hostname: backend
    container_name: backend_container
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    # volumes:
    #   - /home/oshri/Desktop/Develeap/temp/FARM-Stack-Course/backend:/backend/
  
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   image: oshri-portfolio-front
  #   hostname: frontend
  #   container_name: frontend_container
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   # volumes:
  #   #   - /home/oshri/Desktop/Develeap/temp/FARM-Stack-Course/frontend:/backend/

  mongodb:
    hostname: mongodb
    container_name: mongodb_container
    image: bitnami/mongodb
    # ports:
    #   - "27017:27017"
    restart: always

  front:
    hostname: front
    container_name: front_container
    image: oshri-portfolio-front
    build:
      context: .
      dockerfile: Dockerfile.multi
    restart: always
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80