FROM alpine:3.11
WORKDIR /app

# add packages to the images
RUN apk add nodejs && apk add npm


# copy the nexccery content from the local file to the image
COPY frontend/ .


# install npm packages
RUN npm install

ENTRYPOINT [ "npm", "start" ]